export const dummyData = [
  {
    _id: "1",
    title: "title1",
    description: "description1",
    imageUrl: "imageUrl1",
    source: "source1",
  },
  {
    _id: "2",
    title: "title2",
    description: "description2",
    imageUrl: "imageUrl2",
    source: "source2",
  },
  {
    _id: "3",
    title: "title3",
    description: "description3",
    imageUrl: "imageUrl3",
    source: "source3",
  },
  {
    _id: "4",
    title: "title4",
    description: "description4",
    imageUrl: "imageUrl4",
    source: "source4",
  },
  {
    _id: "5",
    title: "title5",
    description: "description5",
    imageUrl: "imageUrl5",
    source: "source5",
  },
  {
    _id: "6",
    title: "title6",
    description: "description6",
    imageUrl: "imageUrl6",
    source: "source6",
  },
  {
    _id: "7",
    title: "title7",
    description: "description7",
    imageUrl: "imageUrl7",
    source: "source7",
  },
  {
    _id: "8",
    title: "title8",
    description: "description8",
    imageUrl: "imageUrl8",
    source: "source8",
  },
  {
    _id: "9",
    title: "title9",
    description: "description9",
    imageUrl: "imageUrl9",
    source: "source9",
  },
  {
    _id: "10",
    title: "title10",
    description: "description10",
    imageUrl: "imageUrl10",
    source: "source10",
  },
  {
    _id: "11",
    title: "title11",
    description: "description11",
    imageUrl: "imageUrl11",
    source: "source11",
  },
  {
    _id: "12",
    title: "title12",
    description: "description12",
    imageUrl: "imageUrl12",
    source: "source12",
  },
  {
    _id: "13",
    title: "title13",
    description: "description13",
    imageUrl: "imageUrl13",
    source: "source13",
  },
  {
    _id: "14",
    title: "title14",
    description: "description14",
    imageUrl: "imageUrl14",
    source: "source14",
  },
  {
    _id: "15",
    title: "title15",
    description: "description15",
    imageUrl: "imageUrl15",
    source: "source15",
  },
  {
    _id: "16",
    title: "title16",
    description: "description16",
    imageUrl: "imageUrl16",
    source: "source16",
  },
  {
    _id: "17",
    title: "title17",
    description: "description17",
    imageUrl: "imageUrl17",
    source: "source17",
  },
  {
    _id: "18",
    title: "title18",
    description: "description18",
    imageUrl: "imageUrl18",
    source: "source18",
  },
  {
    _id: "19",
    title: "title19",
    description: "description19",
    imageUrl: "imageUrl19",
    source: "source19",
  },
  {
    _id: "20",
    title: "title20",
    description: "description20",
    imageUrl: "imageUrl20",
    source: "source20",
  },
];
